version: "3.7"

services:
  db:
    image: postgres:14.3-alpine
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: db_user
      # DO NOT PUT SECRETS IN SOURCE CONTROL
      POSTGRES_PASSWORD: super_secret
    volumes:
      - ./db/dev:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  webapp:
    build: web-app
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      DB_HOST: db
      POSTGRES_DB: example_db
      POSTGRES_USER: db_user
      # DO NOT PUT SECRETS IN SOURCE CONTROL
      POSTGRES_PASSWORD: super_secret
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OKTA_ISSUER_URI: ${ISSUER}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_ID: ${CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET: ${CLIENT_SECRET}
  pwimporthook:
    build: pw-import-hook
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      DB_HOST: db
      POSTGRES_DB: example_db
      POSTGRES_USER: db_user
      SERVER_PORT: 8000
      # DO NOT PUT SECRETS IN SOURCE CONTROL
      POSTGRES_PASSWORD: super_secret
      SPRING_SECURITY_USER_PASSWORD: use-a-strong-password
